/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitypro;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static universitypro.connection.con;

/**
 *
 * @author WAHEEB AL-AQLANY
 */
public final class addStu extends javax.swing.JFrame {

    /**
     * Creates new form addStu
     */
    public addStu() {
        initComponents();
        setLocationRelativeTo(null);
        setStidentToTable();
//        setStidentToTable();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root" , "");

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "error in connection : " + e.getMessage());
        }
    }
    int id , phone2 ;
    String  address , mejor2 ,Name;
DefaultTableModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        refrish = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mejor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stu_name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        stu_id1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setAutoscrolls(true);
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Manage Student");

        refrish.setText("Refrish");
        refrish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(refrish)
                .addGap(225, 225, 225)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refrish))
                .addGap(18, 18, 18))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1, 1010, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 167, 49));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" ID");
        jLabel9.setRequestFocusEnabled(false);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 20, 280, 50);

        mejor.setBackground(new java.awt.Color(0, 51, 51));
        mejor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mejor.setForeground(new java.awt.Color(255, 255, 255));
        mejor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mejor.setSelectionColor(new java.awt.Color(51, 51, 255));
        mejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejorActionPerformed(evt);
            }
        });
        jPanel2.add(mejor);
        mejor.setBounds(100, 270, 370, 40);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Name");
        jLabel10.setRequestFocusEnabled(false);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 140, 170, 31);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setRequestFocusEnabled(false);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 190, 34, 40);

        stu_name.setBackground(new java.awt.Color(0, 51, 51));
        stu_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stu_name.setForeground(new java.awt.Color(255, 255, 255));
        stu_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        stu_name.setName(""); // NOI18N
        stu_name.setSelectionColor(new java.awt.Color(51, 51, 255));
        stu_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_nameActionPerformed(evt);
            }
        });
        jPanel2.add(stu_name);
        stu_name.setBounds(100, 170, 370, 40);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setRequestFocusEnabled(false);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 317, 100, 0);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jLabel11.setRequestFocusEnabled(false);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(100, 320, 280, 50);

        addres.setBackground(new java.awt.Color(0, 51, 51));
        addres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addres.setForeground(new java.awt.Color(255, 255, 255));
        addres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addres.setSelectionColor(new java.awt.Color(51, 51, 255));
        addres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresActionPerformed(evt);
            }
        });
        jPanel2.add(addres);
        addres.setBounds(100, 360, 370, 40);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setRequestFocusEnabled(false);
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 420, 100, 0);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone");
        jLabel15.setRequestFocusEnabled(false);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(100, 430, 280, 50);

        phone.setBackground(new java.awt.Color(0, 51, 51));
        phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        phone.setSelectionColor(new java.awt.Color(51, 51, 255));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel2.add(phone);
        phone.setBounds(100, 470, 370, 40);

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setRequestFocusEnabled(false);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 530, 100, 0);

        stu_id1.setBackground(new java.awt.Color(0, 51, 51));
        stu_id1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stu_id1.setForeground(new java.awt.Color(255, 255, 255));
        stu_id1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        stu_id1.setSelectionColor(new java.awt.Color(51, 51, 255));
        stu_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_id1ActionPerformed(evt);
            }
        });
        jPanel2.add(stu_id1);
        stu_id1.setBounds(100, 50, 370, 40);

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mejor");
        jLabel17.setRequestFocusEnabled(false);
        jPanel2.add(jLabel17);
        jLabel17.setBounds(100, 230, 280, 50);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 700));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        int row = bookTable.getSelectedRow();
        TableModel mo = bookTable.getModel();
        stu_id1.setText(mo.getValueAt(row, 0).toString());
        stu_name.setText(mo.getValueAt(row, 1).toString());
        mejor.setText(mo.getValueAt(row, 2).toString());
        addres.setText(mo.getValueAt(row, 3).toString());
        phone.setText(mo.getValueAt(row, 4).toString());
    }//GEN-LAST:event_bookTableMouseClicked

     // عملية الربط في قاعدة البيانات 
    public boolean DB() {
        boolean isAdded = false;
        id = Integer.parseInt(stu_id1.getText());
        Name = stu_name.getText();
        mejor2 = mejor.getText();
        address = addres.getText();
        phone2 = Integer.parseInt(phone.getText());

        try {
            PreparedStatement pst;
            String sql = "insert into studentu (id,  name , phone, mejor, email) values(? , ? ,? , ?,?)";
            pst = con.prepareStatement(sql);
            pst.setInt(1, id);
            pst.setString(2, Name);
            pst.setInt(3, phone2);
            pst.setString(4, mejor2);
            pst.setString(5, address);
            
            int updateRowCount = pst.executeUpdate();
            if (updateRowCount > 0) {
                isAdded = true;
//                JOptionPane.showMessageDialog(null, "Added");
            } else {
//                JOptionPane.showMessageDialog(null, "Failed adding");
                isAdded = false;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()
            );
        }
        return true;
    }
    // ربط الجدول في قاعدة البيانات 
    public void setStidentToTable() {

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from studentu");
            while (rs.next()) {
                //when add row , all data ara adding again . possible to make if statement 
                // here we make function to delete all data and add with new row
                 id = rs.getInt("id");
                Name = rs.getString("name");
                mejor2 = rs.getString("mejor");
                address = rs.getString("gender");
                phone2 = rs.getInt("phone");
                Object ob[] = {id, Name, mejor2,address, phone2};
                model = (DefaultTableModel) bookTable.getModel();
                model.addRow(ob);
            }

//            PreparedStatement pst = con2.prepareStatement("select * from books");
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(addStu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public boolean update() {
        boolean isUpdated = false;
        id =Integer.parseInt( stu_id1.getText());
        Name = stu_name.getText();
        mejor2 = mejor.getText();
        address = addres.getText();
        phone2 = Integer.parseInt(phone.getText());
        try {
            Connection con = connection.connect();
            String sql = "update studentu set  name = ? , mejor = ? , address = ?  where id= ?";
            PreparedStatement prs = con.prepareStatement(sql);
            prs.setString(1, Name);
            prs.setString(2, mejor2);
            prs.setString(3, address);
            prs.setInt(4, id);
            prs.executeUpdate();
            int rowCount = prs.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(null, "Done");
                isUpdated = true;
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
                return false;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return true;
    }
    
    public boolean delete(){
        id  = Integer.parseInt(stu_id1.getText());
        boolean isdeleted= false;
        try {
             Connection con = connection.connect();
            String sql = "delete from studentu   where id= ?";
            PreparedStatement prs = con.prepareStatement(sql);
            
            prs.setInt(1, id);
           
            int rowCount = prs.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(null, "Done");
                isdeleted = true;
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
                
                isdeleted = false;
            }
        } catch (Exception e) {
        }
        
        return isdeleted;
    }

    public void clearAllData() {
        // this code remove all rows
        this.model = (DefaultTableModel) bookTable.getModel();
        model.setRowCount(0);
    }

    public boolean checkadd() {
        if (stu_id1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter ID");
            return false;
        } else if (stu_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Student Name ");
            return false;
        } else if (mejor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Major");
            return false;
        }
        return true;
    }
    private void mejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mejorActionPerformed

    private void stu_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_nameActionPerformed

    private void addresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (delete() == true) {
            JOptionPane.showMessageDialog(null, "Student has deleted");
            clearAllData();
            setStidentToTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Failed");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addRowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRowsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addRowsMouseClicked

    private void addRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowsActionPerformed
        checkadd();

        
            if (DB() == true) {
                JOptionPane.showMessageDialog(null, "Book added");
                clearAllData();
                setStidentToTable();
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
            }
        

    }//GEN-LAST:event_addRowsActionPerformed

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        if (update() == true) {
            clearAllData();
            update();
            setStidentToTable();
        }
        else{
            //            BreakpointNode.breakpoint();
        }
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void stu_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_id1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ManagerFrame m = new ManagerFrame();
      m.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refrishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrishActionPerformed
        setStidentToTable();
    }//GEN-LAST:event_refrishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addres;
    private rojerusan.RSTableMetro bookTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField mejor;
    private javax.swing.JTextField phone;
    private javax.swing.JButton refrish;
    private javax.swing.JTextField stu_id1;
    private javax.swing.JTextField stu_name;
    // End of variables declaration//GEN-END:variables
}
