/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitypro;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author WAHEEB AL-AQLANY
 */
public class editDoctorF extends javax.swing.JFrame {

    /**
     * Creates new form editDoctorF
     */
    public editDoctorF() {
        initComponents();
    }

    
     public boolean checkadd() {
        if (doc_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter ID");
            return false;
        } else if (subject.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Name of Book");
            return false;
        } else if (addres.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Quantity of books");
            return false;
        }
        return true;
    }
     
      public boolean delete(){
       int id  = Integer.parseInt(id2.getText());
        boolean isdeleted= false;
        try {
             Connection con = (Connection) connection.connect();
            String sql = "delete from books   where id= ?";
            PreparedStatement prs = con.prepareStatement(sql);
            
            prs.setInt(1, id);
           
            int rowCount = prs.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(null, "Done");
                isdeleted = true;
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
                
                isdeleted = false;
            }
        } catch (Exception e) {
        }
        
        return isdeleted;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        doc_name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        id2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" ID");
        jLabel9.setRequestFocusEnabled(false);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 20, 280, 50);

        subject.setBackground(new java.awt.Color(0, 51, 51));
        subject.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subject.setForeground(new java.awt.Color(255, 255, 255));
        subject.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        subject.setSelectionColor(new java.awt.Color(51, 51, 255));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel2.add(subject);
        subject.setBounds(100, 270, 370, 40);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Name");
        jLabel10.setRequestFocusEnabled(false);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 140, 170, 31);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setRequestFocusEnabled(false);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 190, 34, 40);

        doc_name.setBackground(new java.awt.Color(0, 51, 51));
        doc_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doc_name.setForeground(new java.awt.Color(255, 255, 255));
        doc_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        doc_name.setName(""); // NOI18N
        doc_name.setSelectionColor(new java.awt.Color(51, 51, 255));
        doc_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_nameActionPerformed(evt);
            }
        });
        jPanel2.add(doc_name);
        doc_name.setBounds(100, 170, 370, 40);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setRequestFocusEnabled(false);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 317, 100, 0);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        jLabel11.setRequestFocusEnabled(false);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(100, 320, 280, 50);

        addres.setBackground(new java.awt.Color(0, 51, 51));
        addres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addres.setForeground(new java.awt.Color(255, 255, 255));
        addres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addres.setSelectionColor(new java.awt.Color(51, 51, 255));
        addres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresActionPerformed(evt);
            }
        });
        jPanel2.add(addres);
        addres.setBounds(100, 360, 370, 40);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setRequestFocusEnabled(false);
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 420, 100, 0);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone");
        jLabel15.setRequestFocusEnabled(false);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(100, 430, 280, 50);

        phone.setBackground(new java.awt.Color(0, 51, 51));
        phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        phone.setSelectionColor(new java.awt.Color(51, 51, 255));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel2.add(phone);
        phone.setBounds(100, 470, 370, 40);

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setRequestFocusEnabled(false);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 530, 100, 0);

        id2.setEditable(false);
        id2.setBackground(new java.awt.Color(0, 51, 51));
        id2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id2.setForeground(new java.awt.Color(255, 255, 255));
        id2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        id2.setSelectionColor(new java.awt.Color(51, 51, 255));
        id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id2ActionPerformed(evt);
            }
        });
        jPanel2.add(id2);
        id2.setBounds(100, 50, 370, 40);

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Subject");
        jLabel17.setRequestFocusEnabled(false);
        jPanel2.add(jLabel17);
        jLabel17.setBounds(100, 230, 280, 50);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 700));

        kGradientPanel1.setAutoscrolls(true);
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Manage Student");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1, 1000, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 167, 49));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Subject", "Address", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setRowHeight(30);
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 670, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void doc_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_nameActionPerformed

    private void addresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (delete() == true) {
            JOptionPane.showMessageDialog(null, "Student has deleted");
//            clearAllData();
//            setBooksToTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Failed");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addRowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRowsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addRowsMouseClicked

    private void addRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowsActionPerformed
        checkadd();

//        if (DB() == true) {
//            JOptionPane.showMessageDialog(null, "Book added");
//            clearAllData();
//            setBooksToTable();
//        } else {
//            JOptionPane.showMessageDialog(null, "Failed");
//        }

    }//GEN-LAST:event_addRowsActionPerformed

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
//        if (update() == true) {
//            clearAllData();
//            update();
//            setBooksToTable();
//        }
//        else{
//            //            BreakpointNode.breakpoint();
//        }
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerFrame m = new ManagerFrame();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        int row = bookTable.getSelectedRow();
        TableModel mo = bookTable.getModel();
        id2.setText(mo.getValueAt(row, 0).toString());
        doc_name.setText(mo.getValueAt(row, 1).toString());
        subject.setText(mo.getValueAt(row, 2).toString());
        addres.setText(mo.getValueAt(row, 3).toString());
        phone.setText(mo.getValueAt(row, 4).toString());
    }//GEN-LAST:event_bookTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDoctorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDoctorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDoctorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDoctorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDoctorF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addres;
    private rojerusan.RSTableMetro bookTable;
    private javax.swing.JTextField doc_name;
    private javax.swing.JTextField id2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
